{% set name = "azure-mgmt-subscription" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: ddda3bd88f897b7cfff520ac4c0997dba2a078cec6c50a00af30bc61730ca1d3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - msrest >=0.5.0
    - msrestazure >=0.4.32,<2.0.0
    - azure-common ~=1.1

test:
  imports:
    - azure
    - azure.mgmt
    - azure.mgmt.subscription
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/Azure/azure-sdk-for-python
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Microsoft Azure Subscription Management Client Library for Python

extra:
  recipe-maintainers:
    - tim-werner
